CleverCloud/documentation

- content/doc/addons/cellar.md
Fix https://github.com/CleverCloud/documentation/issues/2
> Put the "website bucket" TLS error higher in the document

- content/doc/reference/reference-environment-variables.md
- layouts/partials/index.xml
- layouts/partials/language-specific-deploy/php/index.html
- static/partials/java-versions.md
- static/partials/language-specific-deploy/php.md
This PR update the default runtime version for Java and Php Runtime
To improve documentation by 
_Who should review these changes?_ @judu
> Update default version

- content/doc/metrics/warp10.md
Warp10 documentation told customers to use a Warp10 cluster which isn't alive anymore, `c1` into `c2` :partying_face: 
> fix(warp10): use c2 cluster instead of c1

- assets/css/custom.css
- content/doc/reference/reference-environment-variables.md
- layouts/shortcodes/callout.html
A note about `CC_RUN_COMMAND` with no effect on Docker instances has been added (ran myself into this issue a few days ago), as a default callout.
Took the opportunity to fix dark mode for default callouts. 
Both changes can be compared here: 
- this branch: http://clever-doc-review-cc-run-docker.cleverapps.io/doc/reference/reference-environment-variables/#control-the-deployments-behavior
- main branch: https://developers.clever-cloud.com/doc/reference/reference-environment-variables/#control-the-deployments-behavior
It's needed because otherwise, users will try to add `CC_RUN_COMMAND` to a Docker instance to fix deployment issues, but this won't have any effect and …
> update CC_RUN_COMMAND + fix default callout in dark mode

- content/doc/administrate/log-management.md
- content/doc/reference/reference-environment-variables.md
- fix #3
- fix #16
- fix #23   
I didn't change anything else to logs management page ATM, waiting for new logs stack to be available everywhere for further clarifications.
> Add references to CC_PREVENT_LOGSCOLLECTION, CC_DISABLE_JVM_AGENT and CC_DISABLE_METRICS

- content/doc/administrate/apps-management.md
- content/doc/develop/build-hooks.md
- content/doc/develop/env-variables.md
- content/doc/reference/reference-environment-variables.md
> Add references to CC_DISABLE_BUILD_CACHE_UPLOAD

- static/images/doc/clever-cloud-runners-basic-with-runtimes-alt.svg
The background of the Heptapod SVG was transparent, so it wasn't looking good on dark theme
> fix: add white background to Heptapod SVG

- layouts/changelog/list.html
This PR centers the icon vertically within the heading used for every changelog entry.
Currently it looks like this:
With this PR, it would look like this:
I've only added a few classes to center the icon vertically and add some gap so this should be easy to review if you want to merge it.
This PR may be closed if you think the current icon alignment is fine.
Maybe it's not needed, depends on the alignment you prefer :smile: 
> fix(changelog): adjust the icon alignment inside level 3 headings

- hugo.yaml
- layouts/robots.txt
- layouts/sitemap.xml
Sitemap was generated but not mentioned in `robots.txt`. I added it through a template.
I've set the `baseURL` parameter as [it's needed](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap?hl=en#sitemap-best-practices) to generate full URL for such content.
I also modified [default `sitemap.xml` template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/sitemap.xml) from Hugo to remove some bad links, which are not content we want to link from search engines in sitemap: empty tags/categories or readme pages.
> Add sitemap in robots.txt

- content/doc/CLI/create.md
I found an error in the documentation of the CLI.
`clever create --type php myApp --GitHub owner/myRepo`  
Return: `Unknown option: GitHub`
Change `GitHub` to lowercase `github` because the CLI seems to have case sensitive system.
@juliamrch
> fix(cli) fix Github option to lowercase

- content/doc/administrate/domain-names.md
Prefix routing is lost at the end of the domain names page. We need to rework this page in depth, but in the meantime, put this feature under spotlight through a tip at the beginning of the page could be nice.
> fix: add a prefix routing tip to domain names page

- content/doc/applications/golang/_index.md
- content/doc/reference/reference-environment-variables.md
- static/partials/language-specific-deploy/go.md
Same table/headers in env var reference and Go page, but not as a partial, as it will certainly not be necessary anymore in a coming update
A revamp of the Go deploy documentation, preparing for next steps on this runtime
> fix: Go build/deploy page revamp

- assets/css/custom.css
- content/doc/metrics/new-relic.md
Doc update.
Adding a callout to warn about New Relic's auto-insertion of JavaScript, and explain how to disable it.
An issue was opened: #10.
> Newrelic browser monitoring warn

- content/doc/applications/java/_index.md
This PR attempt to fix broken play1 and 2 links by redirecting to related guide pages.
> fix: play 1 & 2 guide links

- content/changelog/2023-11-10-healthcheck-for-java.md
- content/changelog/2023-11-29-api-update.md
- content/changelog/2023-12-13-cellar-migration-tool-update.md
- content/changelog/2023-12-22-sozu-wider usage.md
- content/changelog/2024-01-15-go-sdk-v0.0.8.md
- content/changelog/2024-01-22-matomo-5.0.1.md
- content/changelog/2024-01-25-clever-tools-3.1.0.md
- content/changelog/2024-01-30-js-client-8.0.3.md
- content/changelog/2024-02-07-clever-tools-3.2.0.md
- content/changelog/2024-02-08-sozu-0.15.19.md
- content/changelog/2024-02-12-new-grahds-region.md
> changelog: spell fixes

- content/doc/administrate/ssl.md
We have found the documentation to be incorrect about TLS certificates to add.
When adding a pem-formatted certificate, if the algorithm is mentionned in the header or footer of a private key, the certificate will not be parsed by [our API ](https://api.clever-cloud.com/v2/certificates/new).
My PR is NOT related to an opened issue but it matches the change made on the API.
Please @juliamrch, @cnivolle
And @KannarFr too (this is a follow-up on the change on the certificate-adding API).
> indicate correct format of private key in  TLS certificates to add

- content/changelog/2024-02-22-postgresql-pgvector-support.md
Add a changelog entry for pgvector support, linked to #200 
> changelog: pgvector support

- content/doc/CLI/getting_started.md
correct docker command with full image name
full docker name of the `docker run` command, ie `clevercloud/clever-tools` (vendor/image-name)  
running the command with just the image name will not work
> correct docker command

- content/doc/reference/reference-environment-variables.md
- static/partials/language-specific-deploy/elixir.md
Versions 1.15 and 1.6 are now available.
> elixir: version bump to 1.15 & 1.16

- hugo.yaml
The frontend team recently migrated to Storybook 7 which changed URLs related to some docs.
The docs website's link to clever-components storybook referred to the `readme` page of the Storybook, which URL has changed.
This PR fixes the URL leading to the clever-components storybook.
**Note**: 
I've set the URL to the exact domain+path of the Storybook app root so that we don't have to change it everytime we change the name of our readme doc or its path.
@juliamrch :innocent:
> fix(main-menu): change the link leading to the clever-components storybook

- layouts/openapi/single.html
Fixes #218
This PR fixes the following issue:
> On the [API v2 page](https://developers.clever-cloud.com/api/v2/), when you type "/" within the filter input field on the left, the focus is moved to the global search input.
It's  a quick fix to an issue caused by 3rd party scripts (`flexSearch` coming from the `Hextra` template).
I'll create an issue + PR on the `Hextra` repo when I have time :wink:  
1. Go to the [API v2 preview page](http://doc-review-pr-219.cleverapps.io/api/v2/),
2. Try to type "/" within the filter input field on the left, it should type the "/" as expected,
3. Click somewhere within the page content (not on a button and not on an input),
4. Type "/" again, the focus should be moved to the global search input :tada: 
@juliamrch
> fix(apiv2-page): prevent conflicts with the global "/" shortcut

- content/changelog/2024-02-27-js-client-8.2.0.md
- content/changelog/2024-03-07-env-vars-app-creation-api.md
- content/changelog/2024-03-07-web-components-v13.md
- content/changelog/2024-03-11-console-components-update.md
- content/changelog/2024-03-12-oauth-token-expiration.md
- content/changelog/2024-03-20-pulsar-3.2.1-update.md
New changelog entries for platforms updates in late february/march. I've put all entries in 1 PR to ease the review process. All co-authors involved already check content.
> changelog: march updates

- content/doc/administrate/domain-names.md
This PR removes the following mention from the [Domain names doc page](https://developers.clever-cloud.com/doc/administrate/domain-names/#using-personal-domain-names):
> Domain names linked to Clever Cloud applications are monitored, so we will send you an email if your DNS configuration is obsolete or incorrect
This mention should be removed because this feature does not exist at the moment.
1. Go to [Using Personal Domain Names section - Domain Names - Preview](http://doc-review-pr-241.cleverapps.io/doc/administrate/domain-names/#using-personal-domain-names),
2. The mention should be gone.
This change has been approved by the traffic team :wink:
@juliamrch
> fix(docs/domain-names): remove auto monitoring mention

- content/guides/tutorial-wordpress.md
Since a few month ago, the MySQL DEV cluster does not listen on 3306 anymore.
Also, the documentation should not encourage using the default MySQL port at all.
> Fix wordpress documentation regarding mysql non-default port.

- .github/pull_request_template.md
Depending where we are, the link can lead to a 404.
in example, in an open issue, since there's no "/blob/main" in the url, the link is broken
> doc: fix link to contributing guidelines

- content/doc/ci-cd/gitlab.md
This update specifies how to configure `PROJECT_PATH` when using a CI/CD component in a project, depending on where the user deploys from: gitlab.com, Heptapod or self-hosted instance.
> CI/CD: add PROJECT_PATH configuration details to prevent errors from users

- content/guides/ruby-rack-app-tutorial.md
This PR adds puma dependency since I had to do it to get the Ruby tutorial working.  
Clever Cloud's deployment task explicitely asked for puma : 
```
[...]
2024-04-28T21:36:26+02:00 No Clever Cloud specific configuration file detected. Continuing…
2024-04-28T21:36:31+02:00 Use ruby 3.3.1
2024-04-28T21:36:33+02:00 puma requested but not present in Gemfile.lock, please run 'bundle add puma'
```
After adding puma :  
```
[...]
2024-04-28T21:37:58+02:00 Use ruby 3.3.1
2024-04-28T21:38:00+02:00 Fetch the dependencies, if you encounters any issue, set 'CC_RUBY_LEGACY' to 'true'
2024-04-28T21:38:03+02:00 Fetching nio4r 2.7.1
2024-04-28T21:38:03+02:00 Installing nio4r 2.7.1 with native extensions
2024-04-28T21:38:03+02:00 Fetching gem metadata from https://rubygems.org/.. …
```
> [Starter Guide - Ruby] puma gem is mandatory

- content/doc/administrate/ssh-clever-tools.md
- content/doc/applications/docker/_index.md
Page: [Lien](https://developers.clever-cloud.com/doc/administrate/ssh-clever-tools/#make-sure-you-have-a-properly-configured-ssh-key)
- Old broken link: https://developers.clever-cloud.com/doc/account/ssh-keys-managmenent
- New updated link: https://developers.clever-cloud.com/doc/account/ssh-keys-management
- [X ] My PR is related to an opened issue : #287 
- [X ] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)
@cnivolle 
@juliamrch
> "SSH key management" page - Dead link update 

- content/doc/best-practices/blue-green.md
- layouts/shortcodes/content/url_healthcheck.md
Blue-green deployment refer to `8080/` to test the health of the system. However, `CC_HEALTH_CHECK_PATH` is more powerful.
This PR will add a reference to the health check page from the blue-green one. And document the default behavior of this health check.
@juliamrch , @cnivolle , @adumas37
> Document usage of CC_HEALTH_CHECK_PATH in blue-green deployment.

- content/doc/quickstart/_index.md
This PR adds the video tutorial in Quickstart section, by embedding it from Youtube, following [the native Hugo feature for external media content](https://gohugo.io/content-management/shortcodes/#youtube).
_Who should review these changes?_ @cnivolle: what do you think of the location of the video? I'm not sure if it's appropriate.
> doc: add demo video to quickstart page

- layouts/shortcodes/content/new-relic.md
_Summarize your changes here : Several pages use the shortcodes layout of new relics to link to our new relics documentation.
The link had a problem and sent to a 404 pages.
Fixed the links so that it should work.
> fix new relics documentation links in shortcodes layout

- content/doc/addons/_index.md
- layouts/partials/shortcodes/card.html
- layouts/shortcodes/card.html
Hextra has modified how the card style is handled. The card functionalities are set in [the partial](https://github.com/imfing/hextra/blob/main/layouts/shortcodes/card.html) and its style is set in `layouts/partials/shortcodes/card.html` ([here](https://github.com/imfing/hextra/blob/main/layouts/partials/shortcodes/card.html)) rather than in the same file. 
Since our partial has been customized to add tags, I've opted for updating our partial in the codebase, to fit Hextra's evolutions, in order to avoid breaking changes in the future, when updating the theme. 
Additionally, [I've opened a PR on Hextra repo](https://github.com/imfing/hextra/pull/427) to propose this feature, so updating our custom partial might not be necessary in the future.
_Who should review these changes?_ @cnivolle
> styles: update card partial to fit current Hextra configuration

- content/doc/CLI/getting_started.md
_Summarize your changes here : 
User with a MacOS that have an apple processor will have the error `Bad CPU type in executable` during clever-tools installation.  
The problem can be easily solved by installing [Rosetta](https://support.apple.com/fr-fr/102527)  
I added a warning at the MacOS section to specify the need of Rosetta in this case and a command to install it.
> Add warning on installing clever tools with apple processor

- content/doc/administrate/cache.md
_Summarize your changes here : Some user may decide to use a monorepo, that means that they may have multiple applications inside one repository.  
In some case, they may want to use Varnish only for some applications, and not all of them.    
The current implementation of Varnish where you need to have a `/clevercloud/varnish.vcl` file at the root cause problem because Varnish would automatically be used with all the app.  
There is a way to resolve that problem by not putting the `varnish.vcl` file at the the root and creating a symlink using deployments hooks.
> Use Varnish in a monorepo

- content/doc/administrate/log-management.md
The ability to export logs using authentication has been added to the CLI, especially for customers requesting help to store and stream logs on Logs Data Platform (OVH service).
This update documents the command and set up needed to do so.
_Who should review these changes?_ @pdesoyres-cc would you try it out and tell where the doc is lacking, eventually?
> doc: document drain log to Logs Data Platform on OVH

- .github/workflows/review-app.yml
- go.mod
- hugo.yaml
This chore configuration sets a minimum (`0.133.0`) and a maximum (`0.133.1`) Hugo version. The minimum is based on potential breaking changes and the maximum is the last tested one.
This solves local errors depending on the installed Hugo version installed across contributors machines. If the installed version is out of scope, the following warning will print:
```shell
WARN  Module "github.com/CleverCloud/documentation" is not compatible with this Hugo version: 0.133.0/0.133.1
```
_Who should review these changes?_ @Kirbeerus could you tell me if this change would be helpful enough for this kind of errors?
> Hugo version setup

- .github/workflows/review-app.yml
- hugo.yaml
This updates the Hugo version to [v0.134.1](https://github.com/gohugoio/hugo/releases/tag/v0.134.1) (latest release) and fixes the `paginate` warning (deprecated since v0.128.0 and soon to be removed) to replace it by `pagination.pagerSize`.
_Who should review these changes?_ @Dekabry
> chore: upgrade from version 0.133.1 to version 0.134.1

- content/changelog/2024-09-03-gitlab-components-review-apps.md
- Replace `GitHub` by `GitLab`
- Add warning for breaking changes if users have set up `deploy` input, which no longer exists
- Specify the use cases for tags (`latest` for tests, version for prod) to avoid breaking pipelines lol 
_Who should review these changes?_ @davlgd
> changelog: fix typo and add breaking changes warning

- content/doc/applications/docker/_index.md
A few clients are confused by the `build` usage in our Docker doc. I've added a section in Docker doc to specify different steps and clarify what happens if no build is required (e.g. in a pre-compiled image use case).
- [Docker doc](http://documentation-pr-379.cleverapps.io/doc/applications/docker/#how-it-works)
_Who should review these changes?_ @BlackYoup wdyt
> doc: specify Docker image steps

- content/changelog/2024-10-01-python-image-changes.md
- content/doc/applications/python/_index.md
- data/runtime_versions.yml
Add en entry about latest Python news and deprecation to come for `3.7`
+ doc update
> changelog: python lifecycle

- content/changelog/2024-04-11-clever-tools-3.5.2.md
- content/changelog/2024-05-28-tasks-in-console.md
- content/doc/best-practices/tips_and_tricks.md
- hugo.yaml
This PR adds Clever Cloud Tips & Tricks initial page. 
It also links Clever Tools GitHub repo as reference for CLI.
> docs: add tips and tricks

- content/doc/reference/reference-environment-variables.md
To use PDFlib or gRPC on a PHP app, you need to use the env var ENABLE_PDFLIB and ENABLE_GRPC.
Currently, they weren't present in the documentation, so i added them to the reference of environnement variables.
> Add new environnment variable to reference

- layouts/shortcodes/software_versions_shared_dedicated.html
The Dev Plan callout is on 2-lines for an only word. I've shortened it to appear on 1 line, removing a superfluous word.
> add-ons: shorten dev plan message

- content/doc/reference/reference-environment-variables.md
3 variables where missing:
`CC_HASKELL_STACK_SETUP_COMMAND` 
`CC_HASKELL_STACK_INSTALL_COMMAND`
`CC_HASKELL_STACK_INSTALL_DEPENDENCIES_COMMAND`
To be used if the default steps from running Haskell aren't enough for the customer:
https://developers.clever-cloud.com/doc/applications/haskell/#mandatory-configuration
> Missing haskell variables

- .github/styles/Clever/hyphens.yml
- .vale.ini
Following discussions on words with an (un)hypenated form, as both are valid, more or less depending on context, I've created a Clever ruleset for Vale with a suggestion rule for such words. `end-of-life` and `up-to-date` are the first concerned here, but we can improve the rule  as we come up with new ideas
> vale: add a suggestion rule for hyphenated words

- content/doc/applications/php/_index.md
Currently, the documentation say that it is impossible to do header injection in PHP with a.htaccess file because php-fpm ignores the mod_headers plugin.
This is not true anymore as php-fpm doesn't ignore mod_headers anymore. You can now set or update headers with .htaccess.  
I modified the documentation to show how to use inject header with .htaccess and also kept the method using PHP.
> Add header injection in PHP with .htaccess

- content/doc/addons/mongodb/_index.md
You currently can't create a mongoDB dev plan.
I added a warning that creating such plan is currently impossible in the documentation.
> Add warning MongoDB dev plan is disabled

- content/changelog/_index.md
Fixing the URL of the RSS feed after the page 1.
> fix: Changelog feed URL after page 1

- .github/external-doc-issue.yml
- .github/workflows/external-doc-update.yml
- .gitignore
- content/guides/astro.md
A Clever Cloud guide has been included on Astro, and therefore we updated as well our guide to include detailed configuration depending on whether it's deployed on a static or a node application.
In order to avoid asynchronicity between our development and the external doc posted on diverse frameworks, I wrote an automation to check if the modified files are linked to some external doc. If relevant, the bot creates an issue and assign it to the PR author, as well as notifying this on a comment.  
- [Updated Astro guide](http://documentation-pr-388.cleverapps.io/guides/astro/)
-  [Demo: Issue created](https://github.com/juliamrch/cc-doc-tests/issues/30)
- [Demo: Comment on PR](https://github.com/juliamrch/cc-doc-tests/pull/29#issuecomment-2387222892)
_Who should review these changes?_ …
> Feat: automate external doc updates

- .github/styles/config/vocabularies/Doc/reject.txt
This PR adds `e-mail(s)` and `plug-in(s)` to reject list. I've based this on doc history and rules in other projects such as Console.
> vale: add e-mail, plug-in to reject list

- content/doc/applications/elixir/_index.md
This PR modifies a link to Elixir documentation, to send to latest version and not one linked to a particular elixir release.
> elixir: bad documentation link

- content/doc/marketplace/_index.md
- content/doc/quickstart/_index.md
Spelling in quickstart and in the marketplace pages.
I'm also adding @vballu to check on the changes in the marketplace page.
> fixing spelling in quickstart and marketplace

- content/doc/addons/cellar.md
Added an example for IP restriction policy on Cellar
> Cellar ip restriction example

- content/doc/CLI/_index.md
The "Manage an application" button was wrongly redirecting to the "Configure" page instead of the "Manage" one. So, I just updated the link.
> Fix link in the index page of the CLI section

- hugo.yaml
- layouts/robots.txt
As the domain is now back to clever-cloud.com, there is no need for a dedicated robots.txt for the documentation
> chore: delete robots.txt

- content/doc/addons/mongodb/_index.md
- content/doc/find-help/faq.md
- layouts/shortcodes/software_versions_shared_dedicated.html
- Created a FAQ entry for DEV plan
- Modified the partial to have a link to FAQ entry
- Cleaned up redundant MongoDB info about DEV plan
- Style & typos 
> DEV FAQ entry + MongoDB clean + partial

- content/doc/find-help/faq.md
Added a note in FAQ to explain how to identify a monitoring request using `X-CleverCloud -Monitoring` header
> X-CleverCloud-Header header to identify a monitoring ping

- content/changelog/2024-12-24-terraform-0.5-Keycloak-Metabase.md
Add an entry about Terraform provider 0.5 with Keycloak/Metabase
> changelog: Terraform provider 0.5

- content/guides/nuxt.md
I will finish after my PR to add a page on the official nuxt doc https://github.com/nuxt/nuxt.com/pull/1668
> Improve Nuxt doc

- .github/workflows/review-app.yml
- content/doc/quickstart/_index.md
- go.mod
- go.sum
- hugo.yaml
Maintenance PR for the site: 
- Upgrade to Hugo [0.140.0]
- Upgrade to [Hextra v0.9.0](https://github.com/imfing/hextra/releases/tag/v0.9.0) (new callouts available)
- fix: 404 on an image 
I injected the environment variables versions to the review app already.
> fix: upgrade hugo version, theme and fix 404 on image

- .github/workflows/external-doc-update.yml
- .github/workflows/review-app.yml
- go.mod
- go.sum
- hugo.yaml
**Upgrades (no breaking changes):**
- Hugo from v0.140.0  to [v0.140.2](https://github.com/gohugoio/hugo/releases/tag/v0.140.2)
- Hextra from v0.9.0 to [v.0.9.3](https://github.com/imfing/hextra/releases/tag/v0.9.3)
**Security update in `external-doc-update.yml`:**
Use the environment parameter in job to avoid giving forks access  to repository secrets.
_The only secret used is `GITHUB_TOKEN`, which is ephemeral: a new one is generated for each job and revoked after the job ends._
_Who should review these changes?_ @cnivolle
> Upgrade Hugo to v0.140.2 and Hextra to v0.9.3

- content/changelog/2024/12-05-metabase-52.md
- content/changelog/2025/01-15-node-22-lts-image-update.md
- content/doc/reference/reference-environment-variables.md
This PR adds an entry about Node.js 22 LTS update with Mise and Redirection.io easy setup
> changelog: Node 22 LTS image, with mise and redirection.io easy setup

- .github/styles/config/vocabularies/Doc/accept.txt
- content/doc/find-help/troubleshooting.md
New section in the doc to inform users about default timeouts (often asked on the Support chat) and ways to eventually bypass them.
> doc: troubleshooting sozu default timeouts

- content/doc/addons/fs-bucket.md
_It is good practice to list SSH public keys that can be used for our services in order to verify the authenticity of remote servers._
> Add SSH/SFTP public keys for FSBucket addons

- content/doc/administrate/ssh-clever-tools.md
- Added a troubleshooting section for `clever SSH`, as it's a common issue.  
> Clever SSH to running instances - Troubleshooting section

- content/doc/applications/docker/_index.md
Specific Docker examples made the page rather cumbersome to read.
- The examples are now links to repos
- Removed  duplicate examples
- Removed HHVM link to sample dockerized application. It's been fixed but requires a separate PR.
> Decluttered Docker examples applications

- content/guides/python-django-sample.md
_Summarize your changes here : 
The python.json file is a legacy tool we do not recommend to use anymore. Instead, we say to use CC_PYTHON_MODULE.
There was still a mention of using python.json in the Django documentation that is not needed anymore.
There is no need to leave this mention of the file as it would only lead to confusion since we don't document it in the other part of the doc.
> remove mention of python.json

- content/doc/marketplace/_index.md
After receiving a privsec breach report, we updated our SSO process. This fixes the main issues:
- Add-on APIs using the example password and sso_salt from this documentation
- The `token` is not signing all the fields that we send to the SSO URL. You can impersonate a user by using their email.
The email has never be documented as a secure identification method, but some providers used it anyway. It’s best to acknowledge the breach and sign the whole body.
@ssauvin
> security: update the SSO process

- .github/styles/config/vocabularies/Doc/accept.txt
- content/doc/applications/php/_index.md
By default, PHP-CLI does not load PHP-FPM `.user.ini` files. The documentation about loading this file was a bit obscure/complicated.
This explanation may be a bit clearer/simpler
> feat(php): better usage/explanation of PHP_INI_SCAN_DIR usage to load FPM values in CLI

- content/doc/metrics/blackfire.md
We support BlackFire with clever cloud only on PHP version 7.4 minimum.
This information wasn't in the documentation before.
> Add minimum version for blackFire

- content/api/v4.md
- content/changelog/2025/01-14-keycloak-26.0.8.md
- content/changelog/2025/01-21-otoroshi-16.22.md
- content/changelog/2025/01-31-keycloak-26.1.md
- content/changelog/2025/02-10-github-action-2.0.md
- content/changelog/2025/02-10-metabase-53.md
- content/changelog/2025/02-11-otoroshi-16.23.md
- content/changelog/2025/02-12-matomo-5.2.2.md
- content/changelog/2025/02-21-keycloak-GA.md
- content/changelog/2025/02-24-metabase-GA.md
- content/changelog/2025/02-26-js-client-9.2.0.md
- content/changelog/2025/02-28-otoroshi-GA-16.24.md
- content/doc/addons/keycloak.md
- content/doc/addons/metabase.md
- content/doc/addons/otoroshi.md
This PR adds entry about latests operators new releases, Operator API and GA
> changelog: operators GA

- content/doc/administrate/network.md
Documentation mentions 4 IP ranges whereas there are only 2 these days. I guess having the number of ranges does not bring any value (because said ranges are specified few lines ahead) so I removed it so it won't be out of sync again.
@davlgd
> fix: remove incorrect mention of the number of IP ranges (Paris region)

- CONTRIBUTING.md
I'm guessing the intended word in this context is `morale` with an `e` at the end.
> Moral and morale differ by one letter, which makes them easy to confuse. Moral can function as an adjective concerned with the principles of right and wrong (a “moral obligation”) or as a noun referring to practices or modes of conduct (to have “good morals”). Morale, on the other hand, functions exclusively as a noun and refers to a sense of enthusiasm shared by a group (“the morale was low”).
https://www.merriam-webster.com/grammar/moral-vs-morale-difference-usage
- [ N/A ] My PR is related to an opened issue : #
I guesse I am currently proving that I've …
> fix(typo): Update CONTRIBUTING.md -- moral vs morale

- content/doc/find-help/faq.md
_Summarize your changes here : The header to identify that a request come from monitoring is called X-Clevercloud-Monitoring and not X-Clever-Monitoring.
fixes #521
> Fix incorrect name for Monitoring header

- content/doc/billing/payments-invoicing.md
_Summarize your changes here : Added mention that invoices are sent to both the primary and secondary mail of the admin and accountant in an organization.
This wasn't mentioned before and can be confusing when it is stated in the console that secondary mail receive no notifications.
> Doc : Add mention that invoices are sent to primary and secondary mail

- content/changelog/2025/03-12-materia-kv-json.md
- content/doc/addons/materia-kv.md
This pull request includes updates to the Materia KV documentation to introduce and explain new JSON functions. The changes include a new changelog entry, updates to the list of supported commands, and detailed examples and limitations of the JSON functions.
Documentation updates:
* [`content/changelog/2025/03-12-materia-kv-json.md`](diffhunk://#diff-453ad2afb454423eab4f207a6efd996633172fce2754b725ac049429e1def791R1-R26): Added a new changelog entry for JSON functions in Materia KV, including new commands and a link to the documentation.
* [`content/doc/addons/materia-kv.md`](diffhunk://#diff-0519774d0fc33316f115382c0c234a214d496af1d560aa202607 …
> feat(materia): document and changelog JSON functions

- content/doc/applications/php/_index.md
This PR removes the instructions about the long-time deprecated `php.json`
> applications(php): delete php.json instructions

- content/doc/addons/cellar.md
- content/doc/administrate/network.md
- content/doc/administrate/ssh-clever-tools.md
- content/doc/develop/healthcheck.md
- content/doc/reference/reference-environment-variables.md
I've made some UI fixes in the titles that appear in the sidebar.
We don't change the `title`, but we add `linkTitle` with a shorter name.
> fix: no more long titles in sidebar

- content/changelog/2025/03-27-postgresql-default.md
This PR adds an entry about PG17 being the default for new created PG databases.
> changelog: PG17 default

- content/guides/_index.md
- content/guides/kubernetes-operator.md
This PR renames `Clever Operator` to a less generic `Clever K8S Operator` (maybe we should also rename the underlying repo/project). It makes more explicit this is link to Kubernetes and avoids confusion with our own operators.
> chore: rename Clever Operator to Clever K8S Operator

- content/doc/applications/php/_index.md
Remove the section about pm.max_children because it's not relevant and makes the documentation ambiguous (pm.max_children cannot be modified in .user.ini)
_Who should review these changes?_ @davlgd
> remove pm.max_children section because it's not relevant

- content/doc/reference/reference-environment-variables.md
_Summarize your changes here : The environnement variable reference page showed that the variable to use accept-routes was called `TAILSCALE_ACCEPT_ROUTE`, but it lack the S at the end.  
The correct one is `TAILSCALE_ACCEPT_ROUTES`
> Fix : typo for tailscale environnement variable 

- .github/workflows/build.yml
- clevercloud-deploy-script.sh
This PR simplifies the deployment script regarding recent images update:
- Hugo is now included in images and there is no need to download it anymore
- Hugo version is set by the new `CC_HUGO_VERSION` environment variable
- The theme is downloaded by hugo during build from the `go.mod` file
- Default destination works right with the documentation/domain
I've updated the build workflow accordingly, as it relies on Ubuntu and needs to download Hugo.
> Simplify deploy script

- content/README.md
- content/changelog/2023/11-29-api-update.md
- content/changelog/2024/01-11-redis-7.2.4.md
- content/changelog/2024/01-24-ruby-3.3.0.md
- content/changelog/2024/02-16-clever-tools-3.4.0.md
- content/changelog/2024/07-03-docker-terraform.md
- content/changelog/2024/07-11-pulsar-3.3.0-update.md
- content/changelog/2024/08-26-java-containers-update.md
- content/changelog/2024/10-01-materia-kv-ttl-layer-update.md
- content/changelog/2024/10-28-pulsar-4.0.0-update.md
- content/doc/account/ssh-keys-management.md
- content/doc/addons/cellar.md
- content/doc/addons/materia-kv.md
- content/doc/addons/mongodb/_index.md
- content/doc/addons/otoroshi.md
- content/doc/applications/golang/_index.md
- content/doc/applications/javascript/nodejs.md
- content/doc/applications/ruby/_index.md
- content/doc/find-help/faq.md
- content/doc/metrics/warp10.md
- content/doc/quickstart/_index.md
- content/guides/ruby-on-rails.md
- content/guides/ruby-rack.md
don't use "here" in links
Don't use "here" in links. It doesn't give much context on the link, is bad for the user experience and accessibility.
https://ux.stackexchange.com/questions/12100/why-shouldnt-we-use-words-such-as-here-and-this-in-textlinks
> fix: Use usefull information in links

- archetypes/applications.md
- content/changelog/2025/06-03-images-update.md
- content/doc/addons/keycloak.md
- content/doc/addons/metabase.md
- content/doc/administrate/cache.md
- content/doc/applications/frankenphp.md
- content/doc/applications/linux.md
- content/doc/applications/static-apache/_index.md
- content/doc/applications/static.md
- content/doc/applications/v.md
- content/doc/cli/applications/_index.md
- content/doc/develop/env-variables.md
- content/doc/reference/reference-environment-variables.md
- layouts/shortcodes/content/mise.md
- layouts/shortcodes/content/redirectionio.md
- layouts/shortcodes/content/varnish.md
This PR adds preliminary documentation for Linux, Static and V new runtimes
> New Linux, Static, V runtimes

- content/api/_index.md
- content/changelog/2024/12-24-terraform-0.5-Keycloak-Metabase.md
- content/doc/addons/_index.md
- content/doc/addons/fs-bucket.md
- content/doc/administrate/apps-management.md
- content/doc/administrate/cron.md
- content/doc/administrate/log-management.md
- content/doc/applications/docker.md
- content/doc/applications/golang.md
- content/doc/applications/ruby.md
- content/doc/applications/rust.md
- content/doc/applications/scala.md
- content/doc/billing/analytics-consumption.md
- content/doc/billing/payments-invoicing.md
- content/doc/billing/unified-invoices.md
- content/doc/cli/_index.md
- content/doc/cli/applications/configuration.md
- content/doc/cli/applications/deployment-lifecycle.md
- content/doc/cli/install/_index.md
- content/doc/cli/notifications-webhooks.md
- content/doc/quickstart.md
- content/doc/reference/reference-environment-variables.md
- content/doc/zz_old_cli/notifications.md
- content/guides/play-framework-2.md
- content/guides/python-django-sample.md
- content/guides/tutorial-drupal.md
- content/guides/tutorial-symfony.md
- content/guides/tutorial-wordpress.md
This PR cleans aliases, removing those starting with `/developers`
As stated [in Hugo documentation](https://gohugo.io/content-management/urls/#aliases):
> An alias with a leading slash is relative to the baseURL
Documentation base URL is `https://www.clever-cloud.com/developers`
> Clean aliases

- content/guides/kibana.md
_Summarize your changes here :   
Some client may want to use multiple auth method to connect to Kibana and not only their clever cloud account. For example to allow some of their external client to connect to it.
This PR give an example to allow to use both Authentification via clever cloud and Kibana authentification.
> Add example for multiple auth to kibana

- README.md
- content/doc/applications/static-apache.md
- content/doc/applications/static.md
- layouts/shortcodes/content-raw.html
- shared/static-guides.md
This PR adds a SSG Guides section to static documentation pages. It uses and documents a new `content-raw` shortcode, which handles shared content including shortcodes.
> Add SSG guides section to static documentation

- assets/css/custom.css
This PR simplifies CSS custom theme, as Hextra evolved a lot since we started using it:
- Removes unnecessary rules, Hextra fixed some problems we previously had
- Uses more Hextra native style to prevent problems we had on lists, callouts with inline code
- Add a hover on content link, reusing a Clever Themed color
Except font, what's kept here could be upstream to Hextra, steps or tables for example are way better so it could be great to provide them to all users and not maintain it from our side.
If we want to keep some other rules, let's discuss it
> chore: simplify CSS custom theme

- README.md
- content/changelog/2024/03-07-web-components-v13.md
- content/changelog/2025/03-07-rust-sdk-0.13.md
- content/changelog/2025/05-06-images-update.md
- content/changelog/2025/05-28-oauth-consumer-new-interface.md
- content/changelog/2025/06-05-api-tokens-console-tips.md
- content/changelog/2025/06-05-oauth-tokens-new-interface.md
- content/changelog/2025/07-02-terraform-0.10.md
- content/doc/addons/cellar.md
- content/doc/addons/otoroshi.md
- content/doc/applications/php.md
- content/doc/applications/static.md
- content/doc/best-practices/tips_and_tricks.md
- content/doc/reference/cli.md
- content/guides/otree.md
- hugo.yaml
This PR:
- moves documentation domain to `clever.cloud` in Hugo config
- updates links to `clever.cloud` when needed
- updates other links to relative form
> chore: move to clever.cloud

- go.mod
- go.sum
- hugo.yaml
- layouts/changelog/single.html
- layouts/docs/single.html
- layouts/openapi/baseof.html
This PR updates Hextra themes to [0.11 release](https://imfing.github.io/hextra/versions/latest/blog/v0.11/). There's only 1 breaking change for us, on breadcrumbs management. I've updated layouts needing it. And also OpenAPI layouts to reproduce upstream changes.
There are lots of new features in this release we could explore in upcoming PRs.
---
---
> Hextra 0.11

- content/changelog/2025/09-01-metabase-56-default.md
This PR adds an entry about Metabase 56 used by default
---
---
---
@allemas
> changelog: Metabase 56 used by default
