CleverCloud/documentation

content/doc/find-help/faq.md
static/partials/java-versions.md

Hey 👋
I'm reopenning the PR I made on the old repo a few days ago.
I also updated a FAQ section about Java class file errors. This solves issue #56.
Have a nice day 😊
Edit: nice work on the new doc website btw

Add Java 21 version support

---

content/doc/administrate/domain-names.md

Hey,
Here it is my first contribution on this new clever documentation 😏
I added the 5 new load balancer IP on the clever paris region 🖥️

Add new IP to the Paris region

---

content/doc/addons/cellar.md

Hey 👋
Here is a PR updating the Java example for Cellar buckets usage, with the latest available AWS SDK version.
This resolves #45

Update cellar java exemple with latest AWS SDK version

---

go.mod
go.sum

Hi,
Just a quick theme bump and some cleaning in go.mod

Bump theme

---

content/doc/administrate/domain-names.md

Fix backtilde in domain name page

Fix domain

---

.github/workflows/review-app.yml
README.md

- Set up SSH and Git
- Check if the PR comes from a fork
- If true, create a new branch and pull changes from the fork
- Add `reopened` as PR status in `deploy` job 
Because current script doesn't deploy branches form forks. This way, external contributors can deploy and see the app as well. Furthermore, some internal contributors prefer to work on their own fork as well.
_Who should review these changes?_ @cnivolle

include forks in review app

---

content/doc/account/_index.md
content/doc/account/administrate-organization.md
content/doc/account/create-account.md
content/doc/account/delete-account.md
content/doc/account/manage-account.md
content/doc/account/notifications.md
content/doc/account/organizations.md
content/doc/account/ssh-keys-management.md

Add description to Account section pages
_Who should review these changes?_ @c

Add description to Account section pages

---

content/doc/addons/redis.md

This tool is disabled in Console
Redsmin is not available anymore to users

Delete reference to Redsmin

---

content/doc/addons/redis.md

Update latest Redis version

---

content/changelog/2024-01-15-go-sdk-v0.0.8.md

changelog: go client v0.0.8

---

content/doc/reference/reference-environment-variables.md

fix: Prometheus port in env vars reference

---

.github/ISSUE_TEMPLATE/new-content-form.yaml

This PR should contain fixes for errors in issues templates.

New content issue template

---

content/doc/addons/elastic/_index.md

- [ X] Documentation content changes
Add a documentation on how to create Index with Elasticsearch
Setting up a clever cloud elasticsearch addon introduce specific settings change (replica at zero)
@davlgd @draescherl  @juliamrch 
closes #143

feat(elasticsearch): add create index doc

---

content/doc/find-help/troubleshooting.md

This page updates the troubleshooting page. The goal is also to have new sections on this page in the future. Like [moderation details](https://github.com/CleverCloud/documentation/issues/151).
Gosh, this page was almost older than me.
@juliamrch

chore: small revamp of the troubleshooting page

---

content/changelog/2024-01-22-matomo-5.0.1.md

Mention Matomo 5.0.1 in changelog

changelog: Matomo 5.0.1

---

assets/css/custom.css
content/doc/administrate/database-migration.md
content/doc/quickstart/_index.md
layouts/shortcodes/callout.html

* Better reading experience with paragraphs margin updates
* implementation of [callouts](https://imfing.github.io/hextra/docs/guide/shortcodes/callout/) in the page **Database Migration**
* reading experience (css, callouts)
* new usage with subtitles

Typography fixes

---

content/changelog/2024-01-25-clever-tools-3.1.0.md

changelog: Clever Tools 3.1.0

---

content/doc/addons/heptapod.md

fix: typography in Heptapod

---

content/changelog/2024-01-10-documentation-changelog.md
content/changelog/2024-01-11-redis-7.2.4.md
content/changelog/2024-01-24-ruby-3.3.0.md

Add support of Ruby 3.3 in changelog + fixes

changelog: Ruby 3.3.0 support

---

content/changelog/2024-01-30-js-client-8.0.3.md

changelog: JS client 8.0.3

---

content/doc/addons/matomo.md

Fix a typo. And went for the wording with hyphen.
We don't like typo.
@juliamrch or @cnivolle

fix: typography in Matomo page

---

content/doc/reference/reference-environment-variables.md

fix(environment): use prefixed version of commit ID

---

assets/css/custom.css

I've changed the CSS selector in order to make links visible in callouts.

fix: links did not appears in callout. Fixed css scope

---

content/doc/administrate/domain-names.md

I update rbx A records in domain page.

Fix rbx IP A records

---

content/doc/applications/docker/_index.md

Explaining that Dockers apps runs inside a VM.
Explaining that Dockers apps runs inside a VM.
Users asked about it.

content: fixing issue #174

---

assets/css/custom.css
content/doc/find-help/troubleshooting.md

The troubleshooting page has been improved.

Troubleshooting page update2

---

static/partials/guides/git-push.md

Add a `clever open` step in the "Git push" partial used in guides

guides: add clever open step to git push partial

---

content/changelog/2024-02-02-images-update.md

Add changelog entry about first part of February images update

changelog: add February images update part 1

---

content/changelog/2024-02-07-clever-tools-3.2.0.md

Add Clever Tools 3.2.0 release to changelog

changelog: Clever Tools 3.2.0

---

go.mod

Fixes #158
Update Hextra theme to the 0.7.2 release with canonical URLs

chore: update to Hextra 0.7.2

---

content/changelog/2024-02-08-sozu-0.15.19.md

Add sozu 0.15.19 release and prepare 1.0 RC

changelog: sozu 0.15.19

---

content/doc/account/ssh-keys-management.md

- Use a wildcard config
- Remove a duplicate section
I followed @BlackYoup recommandations on this
The modified section was not up to date and didn't correspond to the URL we use

fix: update ssh config recommandations

---

content/changelog/2024-02-12-new-grahds-region.md

Add `grahds` entry to changelog

changelog: new grahds region

---

content/doc/extend/add-ons-api.md

fix(add-ons-api): options is now supported

---

content/changelog/2024-02-16-clever-tools-3.4.0.md

Add mention to Clever Tools 3.4.0 to changelog

changelog: Clever Tools 3.4.0

---

go.mod

Fixe #183
It fixes the nested lists issue #183

fix: update Hextra theme to v0.7.3

---

content/doc/addons/jenkins.md

This PR removes the pricing info from the jenkins page.
Because we have decided not to show info about pricing within the documentation pages.
@juliamrch

fix(jenkins): remove pricing information & components

---

content/doc/CLI/create.md
content/doc/administrate/domain-names.md
static/reference/clever-tools/create.md

Remove reference to `jed` as we move to a private region.

doc: reflect middle east evolution

---

content/doc/find-help/troubleshooting.md

Adding a moderation section in troubleshooting page in order to explain how it works at Clever Cloud.
_Who should review these changes?_ @cnivolle

add moderation section in troubleshooting page

---

content/doc/addons/postgresql/_index.md

Update the list of PGSQL available extensions, some text fixes

pgsql: extensions update

---

content/changelog/2024-02-26-mtl-iplb-update.md
content/doc/administrate/domain-names.md

We upgrade LB on MTL, so we need to inform users about new IPs to use in this region. This PR contains the changelog entry and the doc update.

MTL IPs update

---

content/doc/applications/docker/_index.md
content/doc/applications/dotnet/_index.md
content/doc/applications/golang/_index.md
content/doc/applications/javascript/meteor.md
content/doc/applications/javascript/nodejs.md
content/doc/applications/php/_index.md
content/doc/applications/python/_index.md
content/doc/applications/ruby/_index.md
content/doc/applications/rust/_index.md
content/doc/applications/scala/_index.md

Add the "healthcheck" partial to all technologies pages.
@juliamrch

Document deployment healthcheck for all images.

---

content/doc/administrate/log-management.md

This PR suggests to add a section in log management about creating an http drain to collect logs, hosted on Clever Cloud.
_Who should review these changes?_ @juliamrch 
_Commit checked with vale and markdownlint_

Add a section about collecting logs through HTTP

---

assets/css/custom.css
content/doc/extend/add-ons-api.md

Remove highlighting in code blocks (internal issue #57) and fix typos in doc
Code blocks in `.json` present readability issues. [For example](https://developers.clever-cloud.com/doc/extend/add-ons-api/#provisioning): 
This PR modifies the CSS to remove to set a transparent background color and override the theme default color. Typos in `/doc/extend/add-ons-api/` have been fixed as well.
_Who should review these changes?_ @Rachel-nas

chore: fix add-on api page rendering

---

content/doc/administrate/log-management.md

Add ~~third-party~~ community section in log management page in order to put aside those which are not directly supported by Clever Cloud and developed by community.
_Who should review these changes?_ @juliamrch @StevenLeRoux

Add a community software section and move some stuff inside

---

content/doc/applications/ruby/_index.md

New version of Rails which brokes logs in the CC console. Add the new envrionment variables.
@judu

Document changes in Rails logging

---

content/changelog/2024-02-27-images-update-part2.md
content/doc/applications/dotnet/_index.md
content/doc/reference/reference-environment-variables.md

I've added an entry to the new images update and changed default version supported by .Net in documentation at the same time.

changelog: images update part2

---

content/changelog/2024-04-04-CVE-2024-3094.md

Add the entry about CVE-2024-3094

changelog: CVE-2024-3094

---

.github/styles/config/vocabularies/Doc/accept.txt
archetypes/default.md
content/doc/addons/cellar.md

This PR is a revamp of the Cellar documentation with: 
- Updated info (S3 clients examples, bucket name sharing)
- Restructuration: re-organize the info with appropriate shortcodes and improve clarity
- Editorial style update: remove passive voice, clarify some sentences, use a more direct tone and remove time markers as well as drama queen syntax.
- [Current branch](http://doc-review-pr-236.cleverapps.io/doc/addons/cellar/)
- [Main branch](https://developers.clever-cloud.com/doc/addons/cellar/)
_Who should review these changes?_  @BlackYoup

Update Cellar doc

---

content/doc/addons/materia-db-kv.md

Initial documentation for MateriaDB KV before the release of the alpha version
- @davlgd 
- @juliamrch

Initial doc for MateriaDB KV

---

content/doc/billing/payments-invoicing.md
content/doc/billing/unified-invoices.md

We just changed how and when the invoice payments, reminders and service shutdown occurs. This adusts the documentation around these processes.
@geoffrey-guilbon 
@davlgd

Fix invoice payment schedule documentation.

---

layouts/shortcodes/content/url_healthcheck.md

Fix the examples of path to provide for health check configuration.
_Who should review these changes?_ @judu

Fix health check example path

---

content/changelog/2024-04-11-clever-tools-3.5.2.md

Add a mention of Clever Tools 3.5.2 in Changelog

changelog: Clever Tools 3.5.2

---

content/changelog/2024-04-15-new-logs-interface-public-beta.md
content/changelog/2024-04-16-clever-tools-3.6.0.md

add mention of new Logs interface and Clever Tools 3.6.0

changelog: add mention of new Logs interface and Clever Tools 3.6.0

---

content/doc/addons/materia-db-kv.md

Adding some missing commands for MAteriaDB KV
- [x ] I've read the [contributing guidelines](../CONTRIBUTING.md)
@juliamrch

MateriaDB KV - Add last missing commands

---

content/doc/addons/materia-db-kv.md

add a mention of Terraform provider in MateriaDB KV page

docs: add a mention of Terraform provider in MateriaDB KV page

---

content/changelog/2024-04-25-images-update.md

Add an entry about april update to images

changelog: images april 2024 update

---

content/changelog/2024-04-24-php-deprecate-warning.md

Add an entry about coming informative message for PHP deprecated versions

changelog: PHP deprecate warning

---

content/changelog/2024-04-26-new-images-stack.md

Add an entry about new images stack

changelog: new images stack enters production

---

content/doc/reference/reference-environment-variables.md

doc: typo close/closes, better wording

---

content/doc/applications/dotnet/_index.md

Update dotnet documentation with the new demo + fix md syntax errors
_Who should review these changes?_ @s0dyy

update dotnet doc - new demo + md syntax

---

content/doc/applications/javascript/nodejs.md

As we got recent questions about Yarn 4.x deployment, I've made some change to the Node.js page. It completes #258 
- Add details about yarn v3/v4, pnpm, bun, deno
- Some typos/fixes
- Reorganisation
If I made some cosmetic changes, this PR doesn't aim to be a final rewrite. Just a 1st small step. As the Node.js runtime will evolve in the coming weeks, we'll update this page in more depth later.

doc: add details to Node.js deployment

---

content/doc/addons/cellar.md

This update include the following additions to Cellar page:
- A read-only policy example using a second add-on
- A troubleshooting command to prevent errors with s3cmd such as `NotSuchBucket`
_Who should review these changes?_  @BlackYoup

Cellar policy example and s3cmd command troubleshooting

---

content/doc/addons/cellar.md

Reverts CleverCloud/documentation#260

Revert "Cellar policy example and s3cmd command troubleshooting"

---

content/doc/applications/golang/_index.md

As the new Go image with new build/deploy methods is available, I updated the documentation accordingly

go: update deployment instructions

---

content/doc/addons/postgresql/_index.md

Add a warning box on PG custom extension section

Add precisions about DEV plan on custom extensions

---

content/changelog/2024-04-11-clever-tools-3.5.2.md
content/doc/addons/materia-kv.md

Update Materia KV branding in documentation

doc: update Materia KV branding

---

content/changelog/2024-05-30-php-8.3-java-22.md
content/doc/applications/php/_index.md
layouts/shortcodes/content/java-versions.md

Add a changelog entry for PHP 8.3/Java 22 + modifications to documentation pages

changelog: PHP 8.3/Java 22 udpate

---

content/changelog/2024-05-30-php-8.3-java-22.md

fix bad links for phpinfo apps in PHP 8.3 changelog entry

fix: phpinfo apps link in changelog

---

content/changelog/2024-06-07-sozu-1.0.2.md

Add an entry to changelog about Sozu 1.0.2 availability in production

changelog: Sōzu 1.0.2

---

content/doc/addons/materia-kv.md

Add a reference to non TLS port on Materia KV, demos and `clever kv`

docs(kv): add non TLS port, clever kv

---

content/changelog/2024-06-11-clever-tools-3.7.0.md

Add an entry about Clever Tools 3.7

changelog: Clever Tools 3.7

---

content/doc/_index.md
content/doc/extend/_index.md
content/doc/marketplace/_index.md

Following new Marketplace strategy and after discussions with Alliance team, I've moved the Add-on provider section to a 1st level for Marketplace and started to fix content. Most part of the page will be rewritten later after deeper inspection/tests.

docs(marketplace): init section from Add-on provider API page

---

content/doc/marketplace/_index.md

docs(marketplace): fix links

---

content/doc/marketplace/_index.md

Add 301 Redirect and avoid lost referenced pages from google. 
https://www.google.com/search?client=firefox-b-d&q=clever-cloud.com+doc%2Fextend%2Fadd-ons-api%2F
(the first link)

Add 301 Redirect for indexed marketplace pages from google

---

content/doc/reference/reference-environment-variables.md

This PR fixes broken links on hooks env vars.
anyone

fix(environment-variable): fix broken links on hooks

---

content/doc/addons/keycloak.md

This prepare documentation for alpha release of Keycloak add-on. There is now deep changes, mostly reorg/rephrase and small changes:
- no pricing in doc
- no version details in doc
We'll update it further with @allemas during next product iterations.

docs(keycloak): update before alpha

---

content/changelog/2024-06-11-materia-kv-public-alpha.md

Add the entry about Materia KV public alpha

changelog: materia kv public alpha

---

content/changelog/2024-06-28-new-ip-list-paris.md
content/doc/administrate/domain-names.md

- Add a changelog entry about this change

docs: PAR IP update

---

content/changelog/2024-07-01-matomo-5.1.0.md

Add entry about Matomo 5.1.0 release

changelog: Matomo v5.1.0

---

content/changelog/2024-07-02-clever-tools-3.8.0.md

Add entry about Clever Tools 3.8

changelog: Clever Tools 3.8

---

content/doc/addons/keycloak.md

rename Keycloak provider in `clever addon create` instructions

docs(keycloak): rename provider

---

content/doc/administrate/ssl.md

Change in the doc to advise to use` BEGIN PRIVATE KEY` first and try `BEGIN RSA PRIVATE KEY` in case of errors.
@Keksoj

Add custom certificates correction

---

content/changelog/2024-07-03-docker-terraform.md

Add entry about Docker support in Terraform provider

changelog: Docker Terraform support

---

content/changelog/2024-07-04-apache-php-image-update.md

Add a entry about new PHP image with 8.2.21 and 8.3.9

changelog: php 8.2.21 & 8.3.9 image update

---

content/changelog/2024-06-28-new-ip-list-paris.md
content/changelog/2024-07-04-apache-php-image-update.md

changelog: update latest entries

---

content/changelog/2024-07-10-CVE-2024-6387.md

Add changelog entry about CVE-2024-6387

changelog: CVE-2024-6387

---

content/changelog/2024-07-06-mysql-pgsql-update.md
content/doc/addons/postgresql/_index.md

add entry about latest mysql/pgsql updates and update PG extensions documentation

changelog: mysql 8.0.34-26, pgsql 15.7

---

content/changelog/2024-07-05-go-haskell-ruby-update.md

Add entry about July images update

changelog: July images update

---

content/changelog/2024-07-11-pulsar-3.3.0-update.md

Add entry about Apache Pulsar 3.3.0

changelog: Pulsar 3.3.0

---

content/doc/addons/keycloak.md

Keycloak documentation up to date with all supported variables and features

Keycloak documentation : fix variables, hostnames, java flavor

---

content/doc/find-help/troubleshooting.md

_Summarize your changes here : Explanation of the ports a user may see open when they try to scan their domain.

Add Ports explanation to troubleshootingp page

---

content/doc/ci-cd/github.md

Since I've updated the [GH action to deploy review apps](https://github.com/CleverCloud/clever-cloud-review-app), which simplifies its usage, I've updated the documentation as well.
_Who should review these changes?_ @Kirbeerus

doc: update GitHub Action instructions

---

content/doc/administrate/network.md

doc(administrate/network): remove deprecated ips addresses

---

content/doc/find-help/faq.md

Added an explanation of where and how a database backups are stored with cellar and replication.

Database backup explanation

---

content/guides/_index.md
content/guides/hugo-static-s3.md

A full guide on how to host your static website created with Hugo, on Cellar.
+
Updated the index 
_Who should review these changes?_ @juliamrch  @cnivolle

doc: add a guide to host a static website using Hugo + cellar 

---

content/doc/account/administrate-organization.md
content/doc/account/manage-account.md

I've made a clearer page about organisations in order the explain the differences between organizations and Personal Space.
Also, made some vale improv and spelling fixes.

fix: vale and adding info about organizations

---

content/changelog/2024-08-09-python-3.12-update.md

changelog: Python image update

---

content/changelog/2024-08-26-java-containers-update.md
content/doc/applications/java/java-war.md

To begin deprecate/remove old and unused servlet containers, I removed them from the documentation.

Undocument deprecated servlet containers

---

content/changelog/2024-08-30-deploy-url-mtl.md

changelog: new deploy URL on MTL

---

content/doc/addons/postgresql/_index.md

Fix typo in timescaleDB description
- [x ] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)

fix(postgresql): change timescaledb description

---

hugo.yaml

Pagination parameter was not working anymore (maybe because of latest updates). With this fix it's OK. I changed the `pagerSize` value to 21 (half of 42) as it seems sufficient regarding our updates flow.

fix(changelog): pagination parameter

---

content/changelog/2024-09-12-clever-tools-3.8.3.md
content/changelog/2024-09-12-js-client-9.0.0.md

Add entries about Clever Tools 3.8.3 and JS Client 9.0.0

changelog: clever tools 3.8.3 and JS client 9.0.0

---

content/doc/addons/redis.md

Redis uses Elasticsearch versions instead of its own

fix(redis): update versions

---

content/changelog/2024-10-01-materia-kv-ttl-layer-update.md
content/doc/addons/materia-kv.md

Add en entry about Materia KV new layer, with docs update

changelog: Materia KV layer update

---

content/changelog/2024-10-04-keycloak-beta-release.md
content/doc/addons/keycloak.md

changelog entry about KC now available as Beta add-on and doc update

changelog: keycloak beta release

---

content/changelog/2024-10-07-CVE-2024-47561.md

Add an entry about CVE-2024-47561

changelog: CVE-2024-47561

---

content/doc/administrate/domain-names.md

I've change the text and the headers of this page to make it more easy to read and scroll-through.
Note: It will require to change the link to the doc in the pages of domain names https://console.clever-cloud.com/organisations/orga_xxxxx/applications/app_xxxxx/vhosts

fix(domains names):readability and textual updates

---

content/doc/addons/metabase.md

I just thought of a few improvements.
@davlgd

Improve Metabase page

---

content/changelog/2024-10-18-azimutt-available.md

Add an entry about Azimutt availability

changelog: azimutt available

---

content/changelog/2024-10-17-sozu-1.0.5.md

changelog: sozu 1.0.5

---

content/doc/addons/metabase.md

I did more tests of the migration process, so I added details to make it more accurate!
@davlgd

[Metabase] Improve process of migrating from a self-hosted instance

---

content/doc/applications/python/_index.md
content/doc/reference/reference-environment-variables.md

This PR clarifies that `ENABLE_GZIP_COMPRESSION` is specific to Nginx in Python/Ruby

docs(env): clarify ENABLE_GZIP_COMPRESSION is specific to Nginx in Python

---

content/doc/addons/metabase.md

fix(metabase): markdown typos

---

content/changelog/2024-10-28-pulsar-4.0.0-update.md

changelog: Pulsar 4.0.0

---

content/changelog/2024-10-28-metabase-available.md

Adds a mention of Metabase as a Public Beta add-on

changelog: Metabase available

---

content/doc/develop/tasks.md

This PR adds reference to Clever Tasks, based on the previous work by @judu

docs: add Clever Tasks

---

content/changelog/2024-11-11-08-erlang-rust-update.md

Add an entry about Erlang/Rust image update with Redirection.io support

changelog: Erlang & Rust update, Redirection.io support

---

content/changelog/2024-11-08-mysql-mysql-8.4.0.md
content/doc/addons/mysql/_index.md
data/software_versions_shared_dedicated.yml

changelog: MySQL 8.4

---

.github/styles/Google/Acronyms.yml
.github/styles/config/vocabularies/Doc/accept.txt
content/doc/best-practices/tips_and_tricks.md
hugo.yaml

Various updates to match the style guide for the article tips-and-tricks

Tips and tricks update

---

content/doc/reference/reference-environment-variables.md

php8.3 is available in php app
@juliamrch

fix(php): 8.3 is also an option in CC_PHP_VERSION

---

.github/styles/Google/Acronyms.yml
.github/styles/config/vocabularies/Doc/accept.txt
content/doc/best-practices/tips_and_tricks.md
hugo.yaml

Reverts CleverCloud/documentation#426

Revert "Tips and tricks update"

---

content/doc/addons/_index.md
content/doc/addons/matomo.md

This PR reorders add-ons index with categories, such as those of the new creation tunnel

docs: reorder add-ons index

---

content/doc/find-help/faq.md

Fixed two cosmetic typos, I stumbled upon, while reading the documentation.
_Who should review these changes?_ @ I don't know, probably not a big deal this pull request.

Fix two typos

---

content/changelog/2024-11-13-metabase-51-version-warning.md

changelog: Metabase x.51

---

content/changelog/2024-11-13-metabase-51-version-warning.md

Add ressources about Metabase 51 in changelog entry

changelog: add ressources about Metabase 51

---

content/changelog/2024-11-18-keycloak-26.md

changelog: Keycloak 26

---

content/changelog/2024-11-18-keycloak-26.md

Fix a link in latest Keycloak entry in Changelog

Davlgd changelog keycloak 26

---

content/doc/addons/cellar.md

Update S3 client list to add WinSCP and correct filestash link.

Update S3 client list

---

content/doc/marketplace/_index.md

Add a link to the Partner portal in Marketplace page

marketplace: update contact link

---

content/changelog/2024-11-21-eol-warnings-console.md

Add en entry about EOL warnings in the Console

changelog: EOL warnings in Console

---

data/runtime_versions.yml
layouts/shortcodes/runtimes_versions.html

This PR adds a mention to every end-of-life versions in the YAML and a sentence explaining `EOL` acronym to shortcode, with a link to lifecycle info source.

feat(versions): add mention to EOL versions and a source link

---

content/changelog/2024-11-27-elastic-plugins-support.md
content/doc/addons/elastic/_index.md

This PR adds an entry about plugins support for Elastic at creation + doc update

changelog: Elastic update with plugins support

---

content/changelog/2024-11-27-clever-tools-3.10.md

Adds an entry about Clever Tools 3.10 release

changelog: Clever Tools 3.10

---

content/changelog/2024-11-26-keycloak-26.0.06.md

Add an entry about Keycloak 26.0.6

changelog: Keycloak 26.0.6

---

content/doc/administrate/scalability.md
content/doc/quickstart/_index.md

Added pico & nano callout mentionning they have lower priorities (and explaining why sometimes performance might drop).
Added a link from "Quickstart" to "Scalability" to better inform new users about instance sizes.

Nano pico priorities

---

.github/styles/Google/Acronyms.yml
.github/styles/config/vocabularies/Doc/accept.txt
content/changelog/2024-12-04-otoroshi-available.md
content/doc/addons/otoroshi.md

This PR adds an entry about Otoroshi with LLM add-on which is now available and its initial documentation page.

Otoroshi changelog and initial documentation

---

content/changelog/2024-12-12-python-3.13-update.md

fix a sentence in Python 3.13 entry

fix: changelog Python 3.13

---

content/doc/addons/mysql/_index.md

You cannot create trigger or functions on a DEV plan for MySQL add-on.

Ajout restriction trigger et fonction plan dev

---

content/api/howto.md
content/api/v4.md

_Some links were broken in the API documentation, I put the correct links._
- [x ] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)

Fixed broken links in API documentation

---

content/changelog/2024-12-05-metabase-52.md

Add an entry about Metabase 52

changelog: Metabase 52

---

content/doc/applications/docker/_index.md

Deleted a dead link that used to point to a Haskell dockerized example.

Deleted dead link in Docker

---

data/runtime_versions.yml

This PR update the Java EOL source URL

fix: Java EOL source

---

content/changelog/2025/01-22-elixir-1.18-image-update.md
content/doc/reference/reference-environment-variables.md
data/runtime_versions.yml

Add an entry about Elixir 1.18, with documentation update.

Changelog elixir 1.18

---

content/doc/administrate/network.md

_I just fixed the oven by two, because there are no longer 4 but 2 IP ranges_

typo correction in networking and IP adresses ranges

---

content/doc/find-help/troubleshooting.md

This guide provides a method for diagnosing network-related issues using the curl command. By analyzing detailed timing information, you can determine whether problems originate from the network infrastructure, DNS resolution, TLS handshake, or server response

Diag network issue with curl

---

content/doc/applications/javascript/nodejs.md
data/runtime_versions.yml

_Summarize your changes here : update the default node version_

update the default node version

---

content/changelog/2025/02-04-otoroshi-available.md

This PR adds an entry about Otoroshi v16.23.2

changelog: otoroshi v16.23.2

---

content/changelog/2025/02-05-mysql-update.md

Add an entry about MySQL update with `skip-log-bin` option

changelog: mysql update with skip-log-bin

---

content/doc/applications/php/_index.md
data/runtime_versions.yml

This PR add a mention about PHP 7.1 support

add PHP 7.1 support

---

content/changelog/2025/02-20-logs-interface-old-decomission.md
content/doc/administrate/log-management.md

Add a changelog entry about old log stack decommission plan

changelog: old logs stack decommission

---

content/changelog/2025/01-31-keycloak-26.1.md
content/changelog/2025/02-10-github-action-2.0.md
content/changelog/2025/02-10-metabase-53.md
content/changelog/2025/02-11-otoroshi-16.23.md
content/changelog/2025/02-12-matomo-5.2.2.md

This PR fixes versions in latest operators changelogs

changelog: fix operators versions

---

content/doc/addons/metabase.md
content/doc/addons/otoroshi.md

Fixes mention of Keycloak operator in Metabase/Otoroshi pages

docs: fixes Keycloak mention in Metabase/Otoroshi

---

content/changelog/2025/01-31-keycloak-26.1.md
content/changelog/2025/02-21-keycloak-GA.md

Keycloak is not Metabase: I guess there was just a mix of words.
Thank for the news and even more thanks for the work to make Keycloak available on Clever Cloud !
- [ N/A ] My PR is related to an opened issue : #

fix(typo): Update 02-21-keycloak-GA.md -- Keycloak is not Metabase

---

content/changelog/2025/03-03-images-update.md
content/doc/applications/php/_index.md
content/doc/reference/reference-environment-variables.md

This PR adds an entry about march images update, with: 
- updated default Node.js version
- Mention of `CC_APACHE_HEADERS_SIZE`

changelog: march images update

---

content/changelog/2025/03-06-clever-tools-3.9.0.md

This PR adds an entry about WinGet support for Clever Tools

changelog: Clever Tools winget support

---

content/changelog/2025/03-06-clever-tools-winget.md

This PR fixes the WinGet support changelog entry

changelog: fix Clever Tools Winget

---

content/api/_index.md
content/api/howto.md

This PR adds documentation of the Beta API Bridge in the API `How to` section

docs(api): api bridge update

---

content/postmortem/2025-03-03.md

This PR adds the PR of the 03-03 incident

postmortem: 03-03

---

content/postmortem/2025-03-03.md

This PR fixes dates in Frontmatter of 03-03 postmortem

postmortem: fix 03-03 dates in frontmatter

---

content/api/v4.md
content/changelog/2025/03-07-clever-tools-3.12.md
content/doc/develop/network-groups.md

This PR adds an entry about Clever Tools 3.12 and underlying instructions for Network Groups

changelog: Clever Tools 3.12

---

content/changelog/2025/02-17-rust-sdk-0.12.md
content/changelog/2025/03-07-rust-sdk-0.13.md

This PR adds an entry about new Rust SDK versions

changelog: Rust SDK updates

---

content/changelog/2025/03-12-images-update.md
content/changelog/2025/03-12-materia-kv-json.md

Adds an entry about 2025 Week 11 images update

changelog: 2025 W11 images update

---

content/doc/reference/reference-environment-variables.md

Removed socks variables in the reference page. 

Remove Socks section in env var reference page

---

content/changelog/2025/03-18-postgresql-16-17.md

changelog: fix PostgreSQL 16/17

---

content/changelog/2025/03-19-paris-hds.md
content/doc/administrate/domain-names.md
content/doc/cli/applications/_index.md

This PR adds an entry about parhds and update cli/dns documentation

changelog: add parhds

---

content/doc/administrate/domain-names.md

This PR fixes DNS records tables for Paris zones

fix: Paris DNS records

---

content/changelog/2025/02-19-terraform-0.6-redis.md
content/changelog/2025/03-19-terraform-0.7-resources-update.md

This PR add entries about latest Terraform provider updates

changelog: terraform provider update

---

content/changelog/2025/03-19-terraform-0.7-resources-update.md

Fix title of latest Terraform entry

changelog: fix latest Terraform entry title

---

content/doc/addons/metabase.md

Add the password reset procedure to Metabase documentation

add-ons(metabase): add the password reset procedure

---

content/changelog/2025/03-21-php-version-management-update.md
data/runtime_versions.yml

This PR adds an entry about new PHP version management and update supported versions accordingly

changelog: PHP version management update

---

content/changelog/2025/03-21-matomo-5.3.1.md

This PR adds an entry about Matomo 5.3.1 update

changelog: Matomo 5.3.1

---

content/changelog/2025/03-18-images-update-ruby-unified.md

Add an entry about PHP 8.4.5, Unified Ruby and latest images update

changelog: images update 2025 W12

---

content/doc/addons/_index.md

This PR:
- adds Mailpace/Otoroshi
- removes Beta mention from GA add-ons
- fixes some links

addons: update index

---

content/changelog/2025/03-24-postgresql-11-12-eol.md

Adds an entry about PG11/12 support on Clever Cloud

changelog: update on PG11/12 support

---

content/changelog/2025/03-24-otoroshi-update-biscuit-studio-0.10.md

This PR adds an entry about Otoroshi update Biscuit Studio 0.10

changelog: Otoroshi update Biscuit Studio 0.10

---

content/changelog/2025/03-25-js-client-10.0.0.md

This PR adds an entry about JS Client 10.0.0

changelog: JS client 10.0.0

---

content/changelog/2025/03-25-python-3.8-eol.md

This PR adds an entry about Python 3.8 EOL

changelog: Python 3.8 EOL

---

content/doc/cli/applications/configuration.md
layouts/shortcodes/content/set-env-vars.md

This PR fixes more dead links/aliases

chore: fix dead links and aliases

---

.github/styles/config/vocabularies/Doc/accept.txt
content/changelog/2025/03-28-frankenphp-runtime.md
content/doc/applications/frankenphp.md
content/doc/cli/applications/_index.md
content/doc/reference/reference-environment-variables.md

This PR adds documentation and changelog entry about FrankenPHP runtime

Franken PHP

---

content/changelog/2025/03-03-keycloak-26.1.3.md
content/changelog/2025/03-28-keycloak-26.1.4.md

This PR adds an entry about Keycloak 26.1.4

changelog: Keycloak 26.1.4

---

content/doc/applications/php/_index.md
content/doc/applications/static/_index.md

This PR adds "with Apache" mention to PHP/Static runtimes where Apache is used.

doc: add "With Apache" for PHP/Static runtimes

---

content/postmortem/2025-03-03.md

Complete PM 2025 03 03 with databases actions
@CleverCloud/reviewers @StevenLeRoux @davlgd

pm_2025_03_03: complete with dbaas actions

---

content/changelog/2025/02-18-kunernetes-operator-0.6.0.md
content/changelog/2025/03-31-kunernetes-operator-0.7.0.md

This PR adds an entries about latest Clever Kuberrnetes Operator

changelog: Clever Kubernetes Operator v0.7.0

---

content/changelog/2025/04-01-images-update.md

This PR adds an entry about new images

changelog: images update 2025 W13

---

content/changelog/2025/04-02-postgresql-replicas.md
content/doc/addons/postgresql/_index.md

This PR adds a changelog entry about PostgreSQL new replicas management features from the Console and a dedicated `Replication` section in the documentation.

PostgreSQL replicas management update

---

content/changelog/2025/04-01-images-update.md
content/changelog/2025/04-01-otoroshi-17.md
content/changelog/2025/04-03-images-update.md
content/doc/applications/php/_index.md
content/doc/reference/reference-environment-variables.md

This PR adds entry about image update 2025W14, with small fixes and update to doc.

changelog: images update 2025W14

---

content/api/v4.md

This PR updates information about `networkGroup` feature in operators API

api: update network groups endpoints information

---

content/changelog/2025/04-10-mysql-8.4.4-update.md
data/software_versions_shared_dedicated.yml

This PR adds an entry about MySQL 8.4.4-4

Davlgd changelog mysql 8.4.4 4

---

.github/workflows/deploy.yml

This PR adds a link checker in the preview apps workflow. It's quick (about 3 minutes in a GitHub CI) and will help us to detect if a PR adds dead links or if any other link is dead with such a recurrent check.

feat(workflow): add Links checker

---

content/changelog/2025/04-16-images-update.md

This PR adds an entry about images update 2025W16

changelog: images update, 2025W16

---

content/changelog/2025/04-22-metabase-54.md

This PR adds an entry about Metabase 54

changelog: Metabase 54

---

content/changelog/2025/04-22-metabase-54.md

This PR updates Metabase 54 entry links

changelog: update Metabase 54

---

content/changelog/2025/04-24-keycloak-26.2.1-grafana.md
content/doc/addons/keycloak.md

This PR adds an entry about Keycloak 26.2.1 and updates documentation accordingly

changelog: Keycloak 26.2.1

---

content/changelog/2025/01-21-otoroshi-16.22.md
content/changelog/2025/04-25-otoroshi-biscuit-studio-0.0.13.md

This PR adds an entry about Otoroshi with Biscuit Studio 0.0.13

changelog: Otoroshi with Biscuit Studio 0.0.13

---

content/doc/ci-cd/gitlab.md

This PR fixes an URL to Clever Cloud's Console in CI/CD/GitLab page

fix(ci-cd): Console URL

---

content/changelog/2024/03-07-web-components-v13.md
content/doc/applications/php/_index.md
content/doc/best-practices/tips_and_tricks.md
content/doc/cli/_index.md
content/guides/kibana.md
content/guides/node-js-mongo-db.md
content/guides/ruby-rack-app-tutorial.md
content/guides/tutorial-drupal.md

This PR removes not working links, redirections, etc.

fix: bad links removal

---

.github/workflows/deploy.yml

This PR updates `linkchecker` command in workflow:
- Adds a user agent, some link respond with a 403 forbidden HTTP code without it
- Adds an exception for links starting with `https://crates.io/crates/` which need a specific header to send a 200 HTTP Code

workflow: update linkchecker command

---

.github/workflows/build.yml
go.mod
go.sum
hugo.yaml

This PR updates Hugo/Hextra to latest releases

chore: update Hugo to 0.146.7, Hextra to 0.9.7

---

data/software_versions_shared_dedicated.yml

addons(mysql): mark MySQL 5.7 as EOL

---

content/guides/kubernetes-operator.md

This PR expands the Kubernetes Operator guide with comprehensive information about:
- Updated introduction and supported services list
- Detailed authentication methods including CLI configuration extraction
- Latest installation instructions (v1.30.0)
- Flexible deployment options (in-cluster and remote)
- Examples for PostgreSQL and Redis with correct API versions
- Reference to examples directory for other resources
- Troubleshooting section
These enhancements make the guide more comprehensive and user-friendly.

Enhance Kubernetes Operator guide with additional information

---

content/doc/addons/matomo.md

_Summarize your changes here : Added a section to Matomo doc about how to enable the deletion of old date to avoid having the database be completely full.

Doc : How to delete Matomo old archives

---

content/changelog/2025/05-06-redis-8.0.0.md
data/software_versions_shared_dedicated.yml

changelog: Redis 8.0

---

content/changelog/2025/04-16-images-update.md
content/changelog/2025/05-06-images-update.md
data/runtime_versions.yml

This PR adds an entry about images updates 2025W19

changelog: images update, 2025W19

---

content/changelog/2025/05-07-node-24.md

This PR adds an entry about Node.js 24 availability

changelog: Node.js 24

---

content/changelog/2025/04-30-keycloak-26.2.2-security.md
content/changelog/2025/05-06-keycloak-26.2.3.md
content/changelog/2025/05-12-keycloak-26.2.4.md

This PR adds an entry about latest Keycloak updates

changelog: 2505 Keycloak updates

---

content/changelog/2025/05-14-otoroshi-api-env-vars.md
content/doc/addons/otoroshi.md

This PR adds an entry about Otoroshi service dependencies update and adapt documentation to recent changes on Otoroshi add-on URLs.

Davlgd changelog otoroshi api env vars

---

content/changelog/2025/02-05-mysql-update.md
content/changelog/2025/03-18-mysql-update.md
content/changelog/2025/04-10-mysql-8.4.4-update.md
content/changelog/2025/05-15-redis-8.0.1.md
data/software_versions_shared_dedicated.yml

This PR adds an entry about Redis 8.0.1 and fix some typos on previous entries

changelog: Redis 8.0.1

---

content/changelog/2025/05-07-node-24.md
content/changelog/2025/05-16-images-update.md
content/changelog/2025/05-16-node-versions.md
content/doc/applications/javascript/nodejs.md
data/runtime_versions.yml

This PR adds entries about images update, 2025W20-2 and updates Node.js documentation accordingly

changelog: images update, 2025W20-2

---

content/changelog/2025/19-05-otoroshi-17.1.1.md
content/doc/addons/otoroshi.md

This PR adds an entry about Otoroshi v17.1 and updates documentation accordingly

changelog: Otoroshi 17.1

---

content/changelog/2025/05-20-matomo-5.3.2.md

This PR adds an entry about Matomo 5.3.2

changelog: Matomo 5.3.2

---

.github/styles/Google/Acronyms.yml
.github/styles/config/vocabularies/Doc/accept.txt
content/changelog/2025/06-03-native-bun-support.md
content/doc/applications/javascript/_index.md
content/doc/applications/javascript/nodejs.md
data/runtime_versions.yml

This PR adds an entry about Bun native support on Clever Cloud and updates documentation
Don't merge as it's not yet in production

Bun native support

---

content/changelog/2025/06-04-redis-8.0.2.md

This PR adds an entry about Redis 8.0.2

changelog: Redis 8.0.2

---

content/doc/reference/reference-environment-variables.md

This PR fix a bad link to Node version set section

reference(env vars): fix bad link for Node version

---

content/doc/reference/reference-environment-variables.md

This PR adds a section in env vars reference for tools's versions we can set across runtimes and duplicates CC_NODE_VERSION in Node.js section

CC_NODE_VERSION update in env vars reference

---

content/changelog/2025/06-05-mysql-8.0.42-8.4.5.md

This PR adds an entry about MySQL 8.0.42/8.4.5

changelog: mysql 8.0.42 and 8.4.5

---

content/doc/addons/fs-bucket.md

FIx 641 about Health Data Hosting and FS Buckets.

fix #641: Add mention that FS bucket cannot be created on Health region

---

content/doc/applications/javascript/nodejs.md

This PR updates the video at the end of the Node.js page

applications(nodejs): update deployment video

---

content/doc/reference/reference-environment-variables.md

Env var table seems to be malformed 

Fix typo table env var

---

content/doc/applications/php/_index.md

This PR updates PHP extensions support list following (more or less) recent updates

applications(php): update extensions support list

---

content/changelog/2025/06-20-keycloak-26.2.5.md

This PR adds an entry about Keycloak 26.2.5

changelog: keycloak 26.2.5

---

content/changelog/2025/07-02-js-client-11.0.md

This PR adds an entry about JS Client 11.0

changelog: JS Client 11.0

---

content/changelog/2025/07-02-terraform-0.10.md

This PR adds an entry about Terraform 0.10.0

changelog: Terraform 0.10.0

---

content/changelog/2025/07-01-images-update.md
content/changelog/2025/07-04-linux-static-v-runtimes.md

This PR adds an entry about Linux, Static & V runtimes

Linux, Static & V new runtimes

---

content/changelog/2024/01-25-clever-tools-3.1.0.md
content/changelog/2024/02-07-clever-tools-3.2.0.md
content/changelog/2024/02-16-clever-tools-3.4.0.md
content/changelog/2024/04-11-clever-tools-3.5.2.md
content/changelog/2024/04-16-clever-tools-3.6.0.md
content/changelog/2024/06-11-clever-tools-3.7.0.md
content/changelog/2024/07-02-clever-tools-3.8.0.md
content/changelog/2024/09-12-clever-tools-3.8.3.md
content/changelog/2024/10-21-clever-tools-3.9.0.md
content/changelog/2024/11-27-clever-tools-3.10.md
content/changelog/2024/12-18-clever-tools-3.11.md
content/changelog/2025/03-06-clever-tools-winget.md
content/changelog/2025/03-07-clever-tools-3.12.md
content/changelog/2025/06-10-clever-tools-3.13.md
content/doc/applications/static.md
content/doc/metrics/new-relic.md
content/guides/_index.md
content/guides/hugo-static-s3.md
content/guides/ruby-rack-app-tutorial.md
content/guides/ruby-rack.md

This PR mentions auto-build in optimized build cache section and fix links, guides order

applications(static): add mention of auto-build in optimized build cache section

---

content/changelog/2025/07-09-images-update.md
content/doc/applications/frankenphp.md
content/doc/applications/javascript/nodejs.md
content/doc/applications/static.md
content/doc/reference/reference-environment-variables.md
data/runtime_versions.yml
hugo.yaml

This PR adds an entry about 25W28 images update

Images updates 25W28

---

content/changelog/2025/07-10-redis-8.0.3.md

This PR adds an entry about Redis 8.0.3 with JSON module

changelog: redis 8.0.3 with JSON

---

content/changelog/2025/07-08-terraform-0.11.md

This PR adds an entry about Terraform 0.11

changelog: terraform 0.11.0

---

content/changelog/2025/07-10-redis-8.0.3.md

This PR fixes a link in latest Redis changelog entry

changelog: fix Redis JSON link

---

content/doc/addons/pulsar.md

While reading, I thought the text's readbility might benefit from a couple trivial changes. (I might be mistaken about the `user` / `org` id !)
- [don't think so] My PR is related to an opened issue : #

Update pulsar.md -- misc. suggestions

---

layouts/404.html

This PR update image relative path in 404 page and redirection link

fix: 404 image URL

---

content/api/_index.md
content/changelog/2024/01-11-redis-7.2.4.md
content/changelog/_index.md
content/doc/addons/_index.md
content/doc/addons/config-provider.md
content/doc/administrate/ssh-clever-tools.md
content/doc/applications/java/java-war.md
content/doc/applications/php.md
content/doc/best-practices/12-factors.md
content/doc/best-practices/blue-green.md
content/doc/billing/_index.md
content/doc/contribute/_index.md
content/doc/find-help/faq.md
content/doc/metrics/new-relic.md
content/doc/reference/_index.md
content/guides/_index.md
content/guides/proxysql.md
layouts/404.html

This PR adds aliases to manage missing redirections

Davlgd redirections

---

content/doc/addons/fs-bucket.md
content/doc/addons/keycloak.md
content/doc/administrate/cache.md
content/doc/applications/frankenphp.md
content/doc/applications/linux.md
content/doc/applications/nodejs.md
content/doc/applications/php.md
content/doc/applications/static.md
content/doc/applications/v.md
content/doc/cli/applications/_index.md
content/doc/cli/operators.md
content/doc/reference/reference-environment-variables.md

This PR fixes callout syntax, don't use code/links in title (good practice)
Fixes #723

fix: callout syntax, don't use link/code in title

---

content/changelog/2025/07-31-keycloak-26.3.2.md

This PR adds an entry about Keycloak 26.3.2

changelog: Keycloak 26.3.2

---

content/doc/best-practices/tips_and_tricks.md

This PR adds mention of OpenSearch support for Console

best-practices(tips_and_tricks): mention Console OpenSearch support

---

.cursorrules

This PR adds AI instructions to the Clever Cloud documentation: 
- The filename is `.cursorrules` as it's detected by many AI tools, but it can evolve over time
- It's a combination of contribution guidelines, `README.md`, existing content analysis
- It should help to create new pages 1st iteration, rewrite existing, reorganization
- It can also be used locally to use AI to check if a content follows basic rules
Such document should evolve over time to follow ecosystem tools, models, how we write and enhance documentation. The goal here is to init such process, experiment and iterate.

chore: add AI instructions rules

---

.github/styles/config/vocabularies/Doc/accept.txt
CONTRIBUTING.md
README.md

This PR adds a mention of AI instructions and `llms.txt` to README/CONTRIBUTING
It also update some README links to relative format, as it helps during branch reviews

docs: add mention of AI instructions and llms.txt support

---

content/changelog/2025/08-07-images-update.md
content/doc/reference/reference-environment-variables.md
data/runtime_versions.yml

This PR adds an entry about images update, 2025W31

changelog: images update, 2025W31

---

.github/workflows/deploy.yml

This PR names jobs, restrict permissions and don't run links check on `closed`

Deploy action: don't execute links check on closed

---

content/changelog/2025/08-08-metabase-56.md
content/doc/addons/metabase.md

This PR adds an entry about Metabase 56

changelog: Metabase 56

---

content/changelog/2025/08-12-images-update.md
data/runtime_versions.yml

This PR adds an entry about images update 2025W33

changelog: images update, 2025W33

---

.github/styles/config/vocabularies/Doc/accept.txt
content/doc/metrics/warp10.md

Added a link to the list of Telegraf classes in the Warp 10 documentation.
- Closes #
- Related to #
---
---
---
---
<details>
<summary>📋 <strong>For major changes</strong> (click to expand)</summary>
_Describe any specific testing done for complex changes_
_Add screenshots for visual/layout changes_
_List any breaking changes or migration notes_
</details>

Add link to classes list Warp10

---

.github/styles/config/vocabularies/Doc/accept.txt
content/changelog/2025/08-25-keycloak-26.3.3..md

This PR adds an entry about Keycloak 26.3.3
---
---
---
@allemas

changelog: Keycloak 26.3.3

---

content/changelog/2025/08-28-elasticsearch-8.17.4.md
content/doc/addons/elastic.md
data/software_versions_shared_dedicated.yml

This PR adds an entry about Elastic 8.17.4 release
---
---
---
@aurrelhebert

changelog: Elastic 8.17.4

---

.github/styles/config/vocabularies/Doc/accept.txt
content/changelog/2025/08-27-clever-tools-4.0.md

This PR adds an entry about Clever Tools 4.0 release
- Closes #
- Related to #
---
---

changelog: Clever Tools 4.0

---

content/changelog/2025/08-27-clever-tools-4.0.md
content/doc/cli/install/_index.md
content/doc/cli/install/nexus-config.md
content/doc/reference/cli.md

This PR update documentation pages following 4.0.1 release of Clever Tools
---
---

cli: updates following 4.0.1 release

---

content/changelog/2025/09-09-images-update.md
content/doc/applications/frankenphp.md
content/doc/applications/static.md
content/doc/reference/reference-environment-variables.md
data/runtime_versions.yml

This PR adds an entry about images update, 2025W37
---
---
---
@s0dyy

Images update 2025 w37

---

content/changelog/2025/09-16-images-update.md
content/doc/applications/static.md
content/doc/reference/reference-environment-variables.md
data/runtime_versions.yml

This PR adds an entry about 2025W38 images update
---
---
@s0dyy

2025W38 images update

---

content/changelog/2025/09-16-js-client-11.2.md

This PR adds an entry about JS Client 11.2
---
---
@pdesoyres-cc

changelog: JS Client 11.2

---

content/changelog/2025/09-17-clever-tools-4.1.md

This PR adds an entry about Clever Tools 4.1
---
---

Clever Tools 4.1

---

content/doc/reference/products-support.md

Terraform: update support list (addons and runtimes)
---
---
---
---
<details>
<summary>📋 <strong>For major changes</strong> (click to expand)</summary>
_Describe any specific testing done for complex changes_
_Add screenshots for visual/layout changes_
_List any breaking changes or migration notes_
</details>

feat(terraform): update support list, order items

---

content/doc/reference/reference-environment-variables.md

Saw this with a customer and it was the only thing I could see :D
Fix typo in reference env var
---
---
---
<details>
<summary>📋 <strong>For major changes</strong> (click to expand)</summary>
_Describe any specific testing done for complex changes_
_Add screenshots for visual/layout changes_
_List any breaking changes or migration notes_
</details>

Fix typo in reference env var

---

content/changelog/2025/09-30-images-update.md
data/runtime_versions.yml

This PR adds an entry about images update 2025W40
---
---
---
@s0dyy

changelog: images update, 2025W40

---

content/changelog/2025/10-02-keycloak-26.4.0.md

This PR adds an entry about Keycloak 26.4.0 availability
---
---
---
@allemas

changelog: Keycloak 26.4

---

content/changelog/2025/10-07-redis-8.2.2.md
data/software_versions_shared_dedicated.yml

This PR adds an entry about Redis 8.2.2 
---
---
---
@aurrelhebert

changelog: Redis 8.2.2
